# Generated by Django 4.2.5 on 2023-09-19 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='product_picture/image')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'ordering': ['-published_time'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(choices=[('NR', '----'), ('TSH', 'Tashkent shahri'), ('TV', 'Tashkent viloayti'), ('SM', 'Samarqand'), ('SD', 'Buxoro'), ('NY', 'Navoiy'), ('JX', 'Jizzax'), ('AN', 'Andijon'), ('FC', "Farg'ona"), ('NG', 'Namangan'), ('SR', 'Sirdaryo'), ('QR', "Qaraqalpog'iston"), ('XC', 'Xorazm'), ('KC', 'Qashqadaryo'), ('SC', 'Surxondaryo')], default='address', max_length=250)),
                ('count', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(default='')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('YC', 'YANGI BUYURTMALAR'), ('OC', 'DASTAVKAGA TAYYOR '), ('KC', 'Keyin oladi'), ('AC', 'Atkaz')], default='YC', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='shop.product')),
            ],
        ),
    ]
